### PR TITLE
Prepare release v0.4.0

### PR DESCRIPTION
**Pull request by inf17101**
Issues: #330 

**Merge the PR only if all tasks of the issue are resolved.**

# Definition of Done

The PR shall be merged only if all items mentioned in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been followed. In case an item is not applicable as described, please provide a short explanation in the description.

- [x] All steps in [CONTRIBUTING.md](https://github.com/eclipse-ankaios/ankaios/blob/main/CONTRIBUTING.md#how-to-contribute) have been handled

### CODE REVIEW

**Comment by krucod3** [comment]
When #336 is merged, we will need some more changes here as every package will have it's own version.

**Review by krucod3 — APPROVED** [review]
LGTM 👍

**Review by windsource — APPROVED** [review]
LGTM 👍

**Review by inf17101 — COMMENTED** [review]
LGTM 👍

**Pull request merged**
